# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.20.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.20.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bytedance/code/HammingIPv6Scanner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bytedance/code/HammingIPv6Scanner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.20.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.20.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bytedance/code/HammingIPv6Scanner/CMakeFiles /Users/bytedance/code/HammingIPv6Scanner//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bytedance/code/HammingIPv6Scanner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named targets_generate

# Build rule for target.
targets_generate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 targets_generate
.PHONY : targets_generate

# fast build rule for target.
targets_generate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/targets_generate.dir/build.make CMakeFiles/targets_generate.dir/build
.PHONY : targets_generate/fast

#=============================================================================
# Target rules for targets named hamming

# Build rule for target.
hamming: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hamming
.PHONY : hamming

# fast build rule for target.
hamming/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hamming.dir/build.make CMakeFiles/hamming.dir/build
.PHONY : hamming/fast

hamming.o: hamming.cpp.o
.PHONY : hamming.o

# target to build an object file
hamming.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hamming.dir/build.make CMakeFiles/hamming.dir/hamming.cpp.o
.PHONY : hamming.cpp.o

hamming.i: hamming.cpp.i
.PHONY : hamming.i

# target to preprocess a source file
hamming.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hamming.dir/build.make CMakeFiles/hamming.dir/hamming.cpp.i
.PHONY : hamming.cpp.i

hamming.s: hamming.cpp.s
.PHONY : hamming.s

# target to generate assembly for a file
hamming.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hamming.dir/build.make CMakeFiles/hamming.dir/hamming.cpp.s
.PHONY : hamming.cpp.s

targets_generate.o: targets_generate.cpp.o
.PHONY : targets_generate.o

# target to build an object file
targets_generate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/targets_generate.dir/build.make CMakeFiles/targets_generate.dir/targets_generate.cpp.o
.PHONY : targets_generate.cpp.o

targets_generate.i: targets_generate.cpp.i
.PHONY : targets_generate.i

# target to preprocess a source file
targets_generate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/targets_generate.dir/build.make CMakeFiles/targets_generate.dir/targets_generate.cpp.i
.PHONY : targets_generate.cpp.i

targets_generate.s: targets_generate.cpp.s
.PHONY : targets_generate.s

# target to generate assembly for a file
targets_generate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/targets_generate.dir/build.make CMakeFiles/targets_generate.dir/targets_generate.cpp.s
.PHONY : targets_generate.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hamming"
	@echo "... targets_generate"
	@echo "... hamming.o"
	@echo "... hamming.i"
	@echo "... hamming.s"
	@echo "... targets_generate.o"
	@echo "... targets_generate.i"
	@echo "... targets_generate.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

